### ISSUE TITLE
refactor / functionalize the install bash script

### ISSUE THREAD

**Issue by johncoleman83** [johncoleman83/note_taker#1]
The install script, `note_taker/install.bash` runs from the top of the file to the end.  We should functionalize it so that it is separated into separate functions.  Some of it can also be refactored a bit.

**Comment by luisejrobles** [comment]
going to work on it 👍

**Comment by johncoleman83** [comment]
awesome, thanks @luisejrobles !

**Comment by johncoleman83** [comment]
@luisejrobles, we just had a contribution for this, and the author made a bunch of functions... If you can rebase those changes, there is still plenty of refactoring / cleaning of docs that can be done.

**Comment by johncoleman83** [comment]
Otherwise, I may close the ticket, sorry, I just noticed the PR now

**Comment by luisejrobles** [comment]
Ok let me check, no problem

**Comment by luisejrobles** [comment]
Submitting mine as well and if you want me to add docs or something else just let me know alright? I can help you

**Comment by johncoleman83** [comment]
Thanks @luisejrobles, I reviewed your PR, looks good but made a few requests for changes.

**Comment by johncoleman83** [comment]
Closed because this is resolved, pending some refactoring and functionalization by @luisejrobles.
